import Head from "next/head";

import { BaseLayout } from "@/components/layout";
import type { ReactElement } from "react";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <p>
          {status === "loading"
            ? "Loading..."
            : status === "unauthenticated"
              ? "Hello World"
              : `Welcome back, ${session?.user.name}`}
        </p>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <BaseLayout>{page}</BaseLayout>;
};
